// Developer: Nathan Kurz
// Instructor: Betty Kretlow
// File: TokType.java

// Defines Tokens

public enum TokenType {
   IDEN_TKN, DIGIT,
   LEFT_PAREN_TKN, RIGHT_PAREN_TKN, EOS_TKN, PROGRAM_TKN,
   BLOCK_TKN, STATEMENT_TKN, IF_STATEMENT_TKN,
   THEN_STATEMENT_TKN, ELSE_STATEMENT_TKN, 
   WHILE_STATEMENT_TKN, DO_STATEMENT_TKN,
   FOR_STATEMENT_TKN, FUNCTION_STATEMENT_TKN,
   END_STATEMENT_TKN, UNTIL_STATEMENT_TKN,
   PRINT_STATEMENT_TKN, REPEAT_STATEMENT_TKN,
   ASSIGNMENT_STATEMENT_TKN, BOOLEAN_EXPR_TKN,
   ASSIGNMENT_OP_TKN, ARITH_EXPR_TKN, RELATIVE_OP_TKN,
   ARITH_OP_TKN, LITERAL_INTEGER_TKN, INVALID_TKN;
} 